apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: airflow-app
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/maxkrivich/do-argocd-apps.git
    targetRevision: HEAD
    path: deployment/airflow/overlays/dev
    kustomize:
      version: v3.5.4

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
