apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: foo-api
spec:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: foo-api
