apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo-api
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: / 
            pathType: Prefix
            backend:
              service: 
                name: foo-api
                port:
                  number: 80
