apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: foo-api
  labels:
    app: foo-api
  namespace: kube-prometheus-stack
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: foo-api
  endpoints:
  - port: http
    interval: 15s
