apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- patch.yaml

namespace: dev-foo-project


configMapGenerator:
- behavior: merge
  literals:
  - mode="debug"
  name: foo-api-configmap


images:
  - name: foo-api
    newName: maxkrivich/foo-api
    newTag: 0105515a9186ca6d9d810472e2f163ae89698c05


namePrefix: dev-
