apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

namespace: dev-foo-project


configMapGenerator:
- name: foo-api-configmap
  behavior: merge
  literals:
    - mode="debug"


namePrefix: dev-
