apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo-api
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: foo-project
  destination:
    namespace: foo-project-dev
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/maxkrivich/do-argocd-apps.git
    targetRevision: HEAD
    path: deployment/foo/overlays/dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
